"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MobileNavigation from "@/components/common/mobile-navigation";
import { AptosWalletAdapterProvider } from "@aptos-labs/wallet-adapter-react";
import { Network } from "@aptos-labs/ts-sdk";

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen  overflow-hidden")}>
        {/* <FlickeringBackground /> */}
        <AptosWalletAdapterProvider
          // plugins={wallets}
          autoConnect={true}
          dappConfig={{ network: Network.DEVNET }}
          onError={(error) => {
            console.log("error", error);
          }}
        >
          <div className="z-10 flex flex-col h-full">
            <div className="py-3 px-4 z-10 flex-grow overflow-hidden">
              {children}
            </div>
            <MobileNavigation />
          </div>
        </AptosWalletAdapterProvider>
      </body>
    </html>
  );
}
